services:
  postgres:
    container_name: mine_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: mine
      POSTGRES_PASSWORD: mine
      POSTGRES_DB: mine
    volumes:
      - mine_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - mine_network

  redis:
    container_name: mine_redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - mine_redis_data:/data
    networks:
      - mine_network

  minio:
    container_name: mine_minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: mine
      MINIO_ROOT_PASSWORD: password
    command: 'minio server /data/minio --console-address ":8900"'
    volumes:
      - mine_minio_data:/data
    ports:
      - 8900:8900
      - 9000:9000
    networks:
      - mine_network

volumes:
  mine_postgres_data:
  mine_redis_data:
  mine_minio_data:

networks:
  mine_network:
    driver: bridge
