services:
  postgres:
    container_name: mine_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: mine
      POSTGRES_PASSWORD: mine
      POSTGRES_DB: mine
    volumes:
      - mine_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - mine_network

  dragonfly:
    container_name: mine_dragonfly
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    ports:
      - 6379:6379
    volumes:
      - mine_dragonfly_data:/data
    networks:
      - mine_network

  minio:
    container_name: mine_minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: mine
      MINIO_ROOT_PASSWORD: mine1234
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - mine_minio_data:/data
    networks:
      - mine_network

volumes:
  mine_postgres_data:
  mine_dragonfly_data:
  mine_minio_data:

networks:
  mine_network:
    driver: bridge
