services:
  postgres:
    container_name: mine_postgres
    image: postgres:17.2
    environment:
      POSTGRES_USER: mine
      POSTGRES_PASSWORD: mine
      POSTGRES_DB: mine
    volumes:
      - mine_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - mine_network

  minio:
    container_name: mine_minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: mine
      MINIO_ROOT_PASSWORD: mine
    volumes:
      - mine_minio_data:/data
    ports:
      - 9000:9000
    networks:
      - mine_network

volumes:
  mine_postgres_data:

networks:
  mine_network:
    driver: bridge
